import { makeStyles } from "@mui/styles";

export default makeStyles({
    button: {
        border: 'none !important',
        minWidth: '17px !important',
        minHeight: '17px !important',
        marginRight: '1rem !important',
        borderRadius: '50px !important',
    },
    laptopOuterContainer: {
        width: '85%',
        border: '5px solid rgba(24, 24, 24, 0.6)',
        height: '85%',
        zIndex: 10,
        overflow: 'hidden',
        position: 'relative',
        borderRadius: '5px',
        backdropFilter: 'blur(32px)',
    },
    laptopInnerContainer: {
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
    },
    laptopIconWrapper: {
        flex: '1 1 auto',
        padding: '10px',
    },
    laptopNotificationWrapper: {
        top: '0px',
        right: '3px',
        width: '25%',
        height: '100%',
        display: 'flex',
        position: 'absolute',
        flexDirection: 'column-reverse',
        paddingBottom: '3.5rem',
    },
    laptopApp: {
        border: '1px solid transparent',
        height: '71px',
        display: 'flex',
        padding: '10px',
        maxWidth: '100px',
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    laptopAppInnerWrapper: {
        width: '35px',
        height: '40px',
        backgroundColor: '#3c3e45',
        color: '#fff',
        borderRadius: '5px',
        textAlign: 'center',
        fontFamily: 'Arial, Helvetica, sans-serif',
    },
    laptopTaskbarAppInnerWrapper: {
        width: '24px',
        height: '24px',
        backgroundColor: '#3c3e45',
        color: '#fff',
        borderRadius: '5px',
        textAlign: 'center',
        fontFamily: 'Arial, Helvetica, sans-serif',
    },
    laptopNotificationModal: {
        right: '0px',
        width: '25%',
        height: '85%',
        margin: '1rem',
        padding: '20px',
        zIndex: 10,
        position: 'absolute',
        background: 'rgba(24, 24, 24, 0.6)',
        borderRadius: '10px',
        backdropFilter: 'blur(32px)',
    },
    laptopNotificationH1: {
        fontSize: '20px !important',
        textAlign: 'center',
        marginBottom: '1rem !important',
    },
    laptopNotificationModalWrapper: {
        overflow: 'scroll',
        maxHeight: '90%',
    },
    laptopSettingsModal: {
        right: '0px',
        width: '25%',
        height: '85%',
        margin: '1rem',
        padding: '20px',
        zIndex: 10,
        position: 'absolute',
        background: 'rgba(24, 24, 24, 0.6)',
        borderRadius: '10px',
        backdropFilter: 'blur(32px)',
    },
    laptopSettingsH1: {
        fontSize: '20px !important',
        textAlign: 'center',
        marginBottom: '1rem !important',
    },
    laptopSettingsModalWrapper: {
        overflow: 'scroll',
        maxHeight: '90%',
    },
    laptopSettingsInput: { marginBottom: '1rem' },
    laptopSettingsButtons: {
        display: 'flex',
        marginTop: '10px',
        justifyContent: 'space-evenly',
    },
    laptopSettingsButton: {
        color: 'rgb(255, 255, 255)',
        background: 'rgb(19, 85, 167)',
    },
    laptopPresetModal: {
        left: '0px',
        right: '0px',
        width: '50%',
        height: '85%',
        display: 'flex',
        padding: '20px',
        zIndex: 10,
        position: 'absolute',
        flexFlow: 'row wrap',
        background: 'rgba(24, 24, 24, 0.6)',
        marginTop: '1rem',
        marginLeft: 'auto',
        marginRight: 'auto',
        borderRadius: '10px',
        backdropFilter: 'blur(32px)',
        justifyContent: 'center',
    },
    laptopPresetH1: {
        height: '20px !important',
        fontSize: '20px !important',
        textAlign: 'center',
    },
    laptopPresetGrid: {
        height: '100%',
        overflow: 'scroll',
        paddingTop: '1rem',
    },
    laptopTaskbar: {
        left: '0px',
        color: 'rgb(255, 255, 255)',
        width: '100%',
        bottom: '0px',
        height: '40px',
        display: 'flex',
        zIndex: 10,
        position: 'absolute',
        background: 'rgba(24, 24, 24, 0.6)',
        paddingRight: '0.6rem',
        flexDirection: 'row',
        backdropFilter: 'blur(32px)',
    },
    laptopTaskbarApps: {
        flex: '1 1 auto',
        height: '100%',
        display: 'flex',
    },
    laptopTaskbarIcon: { height: '24px' },
    laptopTaskbarTime: {
        display: 'flex',
        fontSize: '11px',
        flexBasis: '63px',
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    laptopTaskbarNotificationsInner: {
        width: '100%',
        border: 'none',
        height: '100%',
        background: 'url(https://i.imgur.com/wADOR0k.png) center center / 16px no-repeat, rgba(255, 255, 255, 0)',
        transition: 'background 0.1s ease 0s',
    },
    gridWrapper: {
        width: '100%',
        border: '2px solid rgba(0, 250, 187, 0.5)',
        height: '100%',
        transition: 'all 150ms ease-in 0s',
        borderRadius: '5px',
    },
    fixWidth: { width: '40px' },
    fixPadding: { padding: '9px' },
});