import { makeStyles } from "@mui/styles";

export default makeStyles({
    root: {
        top: '0px',
        left: '0px',
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        maxWidth: '100vw',
        minWidth: '100vw',
        maxHeight: '100vh',
        minHeight: '100vh',
        pointerEvents: 'none',
        border: '0px',
        margin: '0px',
        outline: '0px',
        padding: '0px',
        overflow: 'hidden',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        '& .MuiInput-root': {
          color: 'white',
          fontSize: '1.3vmin',
        },
        '& .MuiInput-underline:hover:not(.Mui-disabled):before': {
          borderColor: 'white',
        },
        '& .MuiInput-underline:before': {
          borderColor: 'darkgray',
          color: 'blue',
        },
        '& .MuiInput-underline:after': {
          borderColor: 'white',
          color: 'blue',
        },
        '& .MuiInputLabel-animated:before': {
          color: 'darkgray !important',
          fontSize: '1vmin',
        },
        '& .MuiInputLabel-animated:after': {
          color: 'white !important',
          fontSize: '1vmin',
        },
        '& .MuiInputAdornment-root': { color: 'darkgray' },
      },
      mainBox: {
        width: '75vw',
        height: '850px',
        color: 'white',
        display: 'flex',
        overflow: 'hidden',
        position: 'relative',
        maxHeight: '75vh',
        transition: 'none',
        borderRadius: '4px',
        flexDirection: 'row',
        pointerEvents: 'all',
        backgroundColor: 'rgb(34, 40, 49)',
      },
      loadingBox: {
        width: '75vw',
        height: '200px',
        color: 'white',
        display: 'flex',
        overflow: 'hidden',
        position: 'relative',
        maxHeight: '80vh',
        transition: 'all 800ms ease 0s',
        borderRadius: '4px',
        flexDirection: 'row',
        pointerEvents: 'all',
        backgroundColor: 'rgb(34, 40, 49)',
      },
      accountHeader: {
        marginTop: '10px',
        marginLeft: '16px',
      },
      transactionHeader: {
        marginTop: '10px',
        marginLeft: '16px',
      },
      accountWrapper: {
        flexDirection: 'column',
        justifyContent: 'space-evenly',
      },
      cashWrapper: {
        display: 'flex',
        flexDirection: 'column',
        marginLeft: '5%',
        marginTop: '2.7%',
      },

      accountScroll: {
        position: 'fixed',
        justifyContent: 'space-evenly',
        overflowY: 'scroll',
        height: '67vh',
      },
      transactionWrapper: {
        flexDirection: 'column',
        marginLeft: '15rem',
      },
      transactionScroll: {
        position: 'fixed',
        justifyContent: 'space-evenly',
        overflowY: 'scroll',
        height: '70vh',
      },
      accountInnerWrapper: { justifyContent: 'space-evenly' },
      accountLeft: {
        flexDirection: 'column',
        marginLeft: '7px',
        paddingTop: '5px',
      },
      accountRight: {
        flexDirection: 'column',
        marginLeft: '196px',
        marginTop: '-50px',
      },
      accountBox: {
        width: '330px',
        height: '150px',
        backgroundColor: '#30475d',
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
        // marginLeft: '16px',
      },
      spinner: { color: '#bfbfbf' },
      phoneWrapper: {
        top: '0px',
        left: '0px',
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        maxWidth: '100vw',
        minWidth: '100vw',
        maxHeight: '100vh',
        minHeight: '100vh',
        pointerEvents: 'none',
        border: '0px',
        margin: '0px',
        outline: '0px',
        padding: '0px',
        overflow: 'hidden',
      },
      phoneInnerWrapper: {
        top: 'unset',
        left: 'unset',
        right: '328px',
        width: '280px',
        bottom: '-1000px',
        height: '652px',
        zIndex: '20',
        position: 'absolute',
        minWidth: '280px',
        minHeight: '652px',
        pointerEvents: 'all',
        margin: 'unset',
        overflow: 'hidden',
        background:
          'url(https://i.imgur.com/JVPavDg.jpg) 0% 0% / cover no-repeat',
        transition: 'bottom 800ms ease 0s',
        borderRadius: '6px',
        backgroundRepeat: 'no-repeat',
      },
      activeAccountBox: {
        width: '330px',
        height: '150px',
        backgroundColor: '#264361',
        border:"0.3px solid white",
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
      },
      inputLabel: {
        color: 'darkgray !important',
        fontSize:'14px !important',
        '&.focused': { color: 'white !important' },
      },
      leftButton: { float: 'left' },
      rightButton: { float: 'right' },
      transactionBox: {
        width: '1047px',
        height: '200px',
        backgroundColor: '#30475d',
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
        // marginLeft: '16px',
      },
      transactionDivider: {
        color: '#fff',
        borderColor: 'rgba(255, 255, 255, 255)',
      },
      transactionInnerWrapper: { justifyContent: 'space-evenly' },
      transactionSecondInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
      },
      transactionThirdInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
        float: 'right',
        height: '20%',
      },
      transactionFourthInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
        height: '10%',
      },
      transactionLeft: {
        marginLeft: '10px',
        paddingTop: '5px',
      },
      transactionRight: {
        marginLeft: '730px',
        marginTop: '-30px',
      },
      transactionSecondMiddleRight: { marginRight: '15px' },
      transactionThirdMiddle: {
        marginTop: '65px',
        marginLeft: '11px',
      },
      modal: {
        top: '0px',
        left: '0px',
        width: '100%',
        height: '100%',
        display: 'flex',
        zIndex: '1000',
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(155, 155, 156, 0.475)',
      },
      modal_mainBox: {
        width:'30%',
        height: 'auto',
        display: 'flex',
        overflow: 'hidden scroll',
        position: 'relative',
        maxHeight: 'auto',
        minHeight: 'auto',
        backgroundColor: '#30475d',
      },
      transactionMiddleLeft: {
        flex: '33.33%',
        maxWidth: '15%',
        paddingLeft: '10px',
        paddingTop: '5px',
      },
      transactionMiddleMiddle: {
        flex: '33.33%',
        maxWidth: '49.33%%',
        paddingTop: '5px',
      },
      transactionMiddleRight: {
        flex: '33.33%',
        maxWidth: '16.90%',
        paddingLeft: '10px',
        paddingTop: '5px',
      },
});