import { makeStyles } from "@mui/styles";

export default makeStyles({
  debtModalContainer: {
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    display: 'flex',
    zIndex: '1000',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  debtModalInnerContainer: {
    width: 'calc(100% - 64px)',
    height: 'auto',
    display: 'flex',
    padding: '16px',
    overflow: 'hidden scroll',
    position: 'relative',
    maxHeight: '80%',
    minHeight: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(48, 71, 94)',
  },
  debtMessageModalContainer: {
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    display: 'flex',
    zIndex: '1000',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  debtMessageModalInnerContainer: {
    width: 'calc(100% - 64px)',
    height: 'auto',
    display: 'flex',
    padding: '16px',
    overflow: 'hidden scroll',
    position: 'relative',
    maxHeight: '80%',
    minHeight: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(48, 71, 94)',
  },
  debtOuterContainer: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    position: 'absolute',
    bottom: '0%',
    opacity: '1',
  },
  debtInnerContainer: {
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    position: 'absolute',
    transition: 'all 400ms ease 0s',
    willChange: 'left',
  },
  debtSearch: {
    width: '100%',
    height: '64px',
    display: 'flex',
    padding: '8px 16px',
    position: 'relative',
    marginBottom: '8px',
  },
  debtSearchWrapper: {
    width: '100%',
    position: 'relative',
  },
  debtIcon: {
    top: '32px',
    right: '16px',
    display: 'flex',
    zIndex: '1',
    position: 'absolute',
    justifyContent: 'flex-end',
  },
  debtIconWrapper: {
    color: '#fff',
    marginLeft: '16px',
  },
  debtWrapper: {
    maxHeight: '37%',
    width: '100%',
    overflowY: 'auto',
    position: 'absolute',
    top: '10vh',
  },
  loansWrapper: {
    maxHeight: '38%',
    width: '100%',
    overflowY: 'auto',
    position: 'absolute',
    top: '55%',
  },
  debtFees: {
    width: '100%',
    height: 'calc(100% - 72px)',
    padding: '0px 16px',
    maxHeight: 'calc(100% - 72px)',
  },
  debtLoans: {
    width: '100%',
    height: 'calc(100% - 72px)',
    padding: '0px 16px',
    maxHeight: 'calc(100% - 72px)',
  },
  appOuterContainer: {
    position: 'fixed',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  appInnerContainer: {
    backgroundColor: '#fff',
    borderRadius: '4px',
    overflow: 'hidden',
    width: '80%',
    maxWidth: '960px',
    maxHeight: '80%',
    display: 'flex',
    flexDirection: 'column',
  },
  appSearch: {
    backgroundColor: '#f5f5f5',
    padding: '8px',
    borderBottom: '1px solid #e0e0e0',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appSearchWrapper: {
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },

  appIcon: {
    position:'fixed',
    color: 'white',
    right:'29px',
    fontSize:'13px',
    cursor: 'pointer',
  },
  appList: {
    position: 'absolute',
    flexGrow: 1,
    overflowY: 'auto',
    top:'85px',
    width:'100%',
    padding: '16px',
    height:'80%',
  },
});