import { makeStyles } from "@mui/styles";

export default makeStyles({
    root: {
        top: '0px',
        left: '0px',
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        maxWidth: '100vw',
        minWidth: '100vw',
        maxHeight: '100vh',
        minHeight: '100vh',
        border: '0px',
        margin: '0px',
        outline: '0px',
        padding: '0px',
        overflow: 'hidden',
        '& .MuiInput-root': {
          color: 'white',
          fontSize: '1.3vmin',
        },
        '& .MuiInput-underline:hover:not(.Mui-disabled):before': {
          borderColor: 'darkgray',
        },
        '& .MuiInput-underline:before': {
          borderColor: 'darkgray',
          color: 'blue',
        },
        '& .MuiInput-underline:after': {
          borderColor: 'white',
          color: 'blue',
        },
        '& .MuiInputLabel-animated': {
          color: 'darkgray',
          fontSize: '1.5vmin',
        },
        '& .MuiInputAdornment-root': { color: 'darkgray' },
    },
    clothingHeader: {
        display: 'flex',
        width: '100%',
        height: '5%',
        marginBottom: '2vh',
    },
    clothingHeaderInner: {
        display: 'flex',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: '12px',
        paddingRight: '12px',
    },
    clothingInnerContainerWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
        height: '100%',
        maxHeight: '92%',
        overflow: 'auto',
    },
    clothingInnerContainer: {
        display: 'flex',
        flexDirection: 'column',
        width: '95%',
        height: 'max-content',
        borderRadius: '3px',
        marginBottom: '3vh',
        backgroundColor: '#30475e',
    },
    clothingInnerContainerHeader: {
        display: 'flex',
        flexDirection: 'column',
        paddingLeft: '1vh',
        paddingBottom: '1.5vh',
    },
    clothingInnerContainerHeaderSlider: {
        display: 'flex',
        flexDirection: 'column',
        paddingLeft: '1vh',
    },
    clothingInnerContainerInputWrapper: {
        display: 'flex',
        flexDirection: 'unset',
        paddingLeft: '1vh',
        paddingBottom: '1vh',
    },
    clothingLeftSidebar: {
        display: 'flex',
        alignItems: 'flex-end',
        flexDirection: 'column',
        width: '100px',
        height: '100%',
    },
    clothingLeftSideBarTab: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '40%',
        height: '4%',
        backgroundColor: 'rgb(34, 40, 49)',
        borderRadius: '3px',
        marginTop: '5%',
        marginRight: '5%',
    },
    clothingContainer: {
        display: 'flex',
        width: '490px',
        height: '100%',
        backgroundColor: 'rgb(34, 40, 49)',
        flexDirection: 'column',
    },
    clothingRightSidebar: {
        display: 'flex',
        width: '4vw',
    },
    clothingRightSidebarInner: {
        display: 'flex',
        justifyContent: 'center',
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        backgroundColor: '#30475e',
    },
    clothingRightSidebarIcon: {
        display: 'flex',
        justifyContent: 'center',
        paddingTop: '0.5vh',
        paddingBottom: '0.5vh',
    },
    clothingRightSidebarTabs: {
        display: 'flex',
        height: '100%',
        alignItems: 'center',
        flexDirection: 'column',
    },
    clothingRightSidebarTab: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '5.5%',
        width: '100%',
        cursor: 'pointer',
    },
});