import { makeStyles } from "@mui/styles";

export default makeStyles({
  root: {
    top: '0px',
    left: '0px',
    width: '100vw',
    height: '100vh',
    position: 'absolute',
    maxWidth: '100vw',
    minWidth: '100vw',
    maxHeight: '100vh',
    minHeight: '100vh',
    pointerEvents: 'none',
    border: '0px',
    margin: '0px',
    outline: '0px',
    padding: '0px',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& .MuiInput-root': {
      color: 'white',
      fontSize: '1.3vmin',
    },
    '& .MuiInput-underline:hover:not(.Mui-disabled):before': {
      borderColor: 'darkgray',
    },
    '& .MuiInput-underline:before': {
      borderColor: 'darkgray',
      color: 'blue',
    },
    '& .MuiInput-underline:after': {
      borderColor: 'white',
      color: 'blue',
    },
    '& .MuiInputLabel-animated:before': {
      color: 'darkgray !important',
      fontSize: '1vmin',
    },
    '& .MuiInputLabel-animated:after': {
      color: 'white !important',
      fontSize: '1vmin',
    },
    '& .MuiInputAdornment-root': { color: 'darkgray' },
  },
  callModalContainer: {
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    display: 'flex',
    zIndex: '1000',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  callModalInnerContainer: {
    width: 'calc(100% - 64px)',
    height: 'auto',
    display: 'flex',
    padding: '16px',
    overflow: 'hidden scroll',
    position: 'relative',
    maxHeight: '80%',
    minHeight: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(48, 71, 94)',
  },
  callMessageModalContainer: {
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    display: 'flex',
    zIndex: '1000',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  callMessageModalInnerContainer: {
    width: 'calc(100% - 64px)',
    height: 'auto',
    display: 'flex',
    padding: '16px',
    overflow: 'hidden scroll',
    position: 'relative',
    maxHeight: '80%',
    minHeight: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(48, 71, 94)',
  },
  appOuterContainer: {
    position: 'fixed',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  appInnerContainer: {
    backgroundColor: '#fff',
    borderRadius: '4px',
    overflow: 'hidden',
    width: '80%',
    maxWidth: '960px',
    maxHeight: '80%',
    display: 'flex',
    flexDirection: 'column',
  },
  appSearch: {
    backgroundColor: '#f5f5f5',
    padding: '8px',
    borderBottom: '1px solid #e0e0e0',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appSearchWrapper: {
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },

  appIcon: {
    position:'fixed',
    color: 'white',
    right:'38px',
    fontSize:'13px',
    cursor: 'pointer',
  },
  appList: {
    position: 'absolute',
    flexGrow: 1,
    overflowY: 'auto',
    top:'85px',
    width:'100%',
    padding: '16px',
    height:'80%',
  },
});