local function restartUI(withMsg)
  SendUIMessage({ source = "FIXDEV-nui", app = "main", action = "restart" });
  if withMsg then
    TriggerEvent("DoLongHudText", "You can also use 'ui-r' as a shorter version to restart!")
  end
  TriggerScreenblurFadeOut(100.0)
  TriggerEvent('closeInventoryGui')
  TriggerEvent('FIXDEV-financials:ResetUI')
  TriggerEvent('FIXDEV-radio:ResetUI')
  TriggerEvent('FIXDEV-menu:ResetUI')
  TriggerEvent('FIXDEV-interact:ResetUI')
  TriggerEvent('FIXDEV-mdt:ResetUI')
  TriggerEvent('FIXDEV-ui:restartUI')
  TriggerEvent('menu:menuexit')
  TriggerEvent('clothing:close')
  exports['FIXDEV-interface']:showInteraction("Restarting UI .")
  Wait(1000)
  exports['FIXDEV-interface']:showInteraction("Restarting UI ..")
  Wait(1000)
  exports['FIXDEV-interface']:showInteraction("Restarting UI ...")
  Wait(1000)
  exports['FIXDEV-interface']:showInteraction("UI Successfully Restarted")
  Wait(1000)
  exports['FIXDEV-interface']:hideInteraction()
  --TriggerEvent("FIXDEV-hud:initHud")
  initHud()
  TriggerEvent("FIXDEV-hud:restarted")
  SendUIMessage({ app = "hud", data = { display = true }, source = "FIXDEV-nui" })
  local cj = exports["police"]:getCurrentJob()
end
RegisterCommand("FIXDEV-hud:restart", function() restartUI(true) end, false)
RegisterCommand("ui-r", function() restartUI() end, false)
RegisterNetEvent("FIXDEV-hud:server-restart")
AddEventHandler("FIXDEV-hud:server-restart", restartUI)